# Generated by Django 5.0 on 2024-08-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalteam',
            name='Medicalid',
        ),
        migrations.RemoveField(
            model_name='sponserdetail',
            name='sponserid',
        ),
        migrations.RemoveField(
            model_name='sponsership',
            name='sponserid',
        ),
        migrations.RemoveField(
            model_name='sponsership',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='userid',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
