# Generated by Django 5.1 on 2024-08-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0002_remove_medicalteam_medicalid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='name',
            new_name='uname',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='photo',
            new_name='uphoto',
        ),
        migrations.RemoveField(
            model_name='sponserdetail',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sponserdetail',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='sponserdetail',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='name',
        ),
        migrations.AddField(
            model_name='sponserdetail',
            name='semail',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sponserdetail',
            name='smobile_no',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sponserdetail',
            name='sname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sponsership',
            name='semail',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sponsership',
            name='smobile_no',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sponsership',
            name='sname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sponsership',
            name='uaddress',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sponsership',
            name='ulocation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sponsership',
            name='umobile_no',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sponsership',
            name='uname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sponsership',
            name='uphoto',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='uaddress',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='ulocation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='umobile_no',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='uname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
