# Generated by Django 5.1 on 2024-08-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0004_sponsordetail_rename_sponsership_sponsorship_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsordetail',
            name='cardnumber',
        ),
        migrations.RemoveField(
            model_name='sponsordetail',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='sponsordetail',
            name='month',
        ),
        migrations.RemoveField(
            model_name='sponsordetail',
            name='year',
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='cardnumber',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='cvv',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='month',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
