# Generated by Django 5.1 on 2024-08-27 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0005_remove_sponsordetail_cardnumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsordetail',
            name='semail',
        ),
        migrations.RemoveField(
            model_name='sponsordetail',
            name='sname',
        ),
    ]
