# Generated by Django 5.0 on 2024-08-27 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0006_remove_sponsordetail_semail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='uname',
        ),
    ]
