# Generated by Django 5.1 on 2024-10-17 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0008_contact_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='info',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='mobile_no',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='uname',
        ),
    ]
