# Generated by Django 5.0 on 2024-10-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0009_rename_info_contact_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
